tbd_tpcdi:
  target: dev
  outputs:
    dev:
      type: spark
      method: session
      schema: demo
      host: NA                           # not used, but required by `dbt-core`
      server_side_parameters:
        "spark.log.level": "INFO"
        "spark.master": "yarn"
        "spark.submit.deployMode": "client"
        "spark.driver.port": "30000"
        "spark.blockManager.port": "30001"
        "spark.driver.host": "10.11.0.5"
        "spark.driver.bindAddress": "0.0.0.0" #FIXME: create a command to get it
        "spark.driver.memory": "2g"
        "spark.executor.memory": "4g"
        "spark.executor.instances": "2"
        "spark.hadoop.hive.metastore.warehouse.dir": "hdfs:///user/hive/warehouse/"