version: 2

sources:
  - name: reference
    database: digen
    loader: tpcdi.py

    tables:
      - name: status_type
      - name: industry
      - name: date
      - name: tax_rate
      - name: trade_type