version: 2

sources:
  - name: bronze
    schema: glue_catalog.bronze_ice
    loader: tpcdi.py

    tables:
      - name: crm_customer_mgmt
      - name: reference_tax_rate
      - name: brokerage_cash_transaction
      - name: accounts
      - name: finwire_company
      - name: finwire_financial
      - name: finwire_security
      - name: bronze.finwire_security
      - name: reference_status_type
      - name: reference_trade_type
      - name: reference_industry
      - name: reference_date
      - name: hr_employee
      - name: brokerage_holding_history
      - name: brokerage_trade
      - name: brokerage_trade_history
      - name: brokerage_daily_market
      - name: brokerage_watch_history